require('sanitize-html/dist/sanitize-html.js');
require('angularjs-dragula/dist/angularjs-dragula.js');
require('jmap-draft-client/dist/jmap-draft-client.js');
require('ui-select/dist/select.js');
require('esn-frontend-common-libs/src/frontend/vendor-libs.js');
require('./esn.inbox.libs/app/app.module.js');
require('esn-frontend-inbox-calendar/src/index.js');
require('./app/app.js');
require('./all.less');
