require('sanitize-html/dist/sanitize-html.js');
require('angularjs-dragula/dist/angularjs-dragula.js');
require('jmap-draft-client/dist/jmap-draft-client.js');
require('ui-select/dist/select.js');
require('esn-frontend-common-libs/src/index.js');
require('./require-angular-injections.js');
require('./linagora.esn.james/app/app.module.js');
require('./linagora.esn.unifiedinbox/app/app.js');
require('./all.less');
